### ISSUE TITLE
Timeline view: When zoomed, clicking on a card doesn't open the card

### ISSUE THREAD

**Issue by gholin** [cameronsutter/plottr_electron#107] opened 2017-04-12 17:55 UTC
Steps to repro:
1. On Timeline view, pick a zoom level and zoom in or out
2. Try clicking on a card.

Result:
The screen reverts back to normal view. Clicking on the card now will actually open it up.
Found in v.0.9

**Comment by cameronsutter** [comment] 2017-04-18 20:45
This might be intended behavior. i remember talking about this when we first made it. We should review it

**Comment by cameronsutter** [comment] 2019-04-08 19:01
Fixed in a recent commit

**Closed by cameronsutter** 2019-04-08 19:01 UTC
Labels: UI, bug
